### ISSUE TITLE
Bug: incompatible with remote TRAMP

### ISSUE THREAD

**Issue by p3r7** [terjesannum/emacs-influxdb-mode#1]
Hello,

Why let-binding `default-directory` to a local path (`~`)?

This forces command `influx` to use local _influx_ executable, thus preventing using one from a remote server (via TRAMP).

I don't really see how going to `~` is usefull for the rest of the code.

**Comment by terjesannum** [comment]
Ah, yes I can see that it causing problems in that case. For me it was the other way, with a lot of remote buffers I wanted to be able to get an influx cli on localhost with `M-x influx`.
I'll add a fix for this, thanks for reporting.
